spring.application.name=order-study
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_study}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:order}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:order}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
